<#
 Purpose:      Pulls down updates using WSUS Offline ( http://download.wsusoffline.net/ ), unpacks them, uploads them
               to the deployment server, and then updates the PDQ job file.
 Requirements: 1. Write-access to the repo (network share) on the deployment server
               2. 7z.exe
               3. RunAll.cmd update script, generated by WSUS Offline. This tells WSUS offline what to grab
               4. Exported XML job file from PDQ Deploy to update (e.g. "Microsoft Offline Updates.xml")
               5. This script assumes WSUS Offline pulls down updates for ALL products at the same time. That is, when
                  it goes to update the PDQ job file, it assumes all packages were refreshed at the same time.
 Author:       reddit.com/user/vocatus ( vocatus.gate@gmail.com ) // PGP key: 0x07d1490f82a211a2
 History:      1.5.4 * Fix syntax errors and duplicated content
               1.5.3 * Minor cleanup
               1.5.2 * Convert standalone variables to parameter block to support CLI use
               1.5.1 - Remove requirement and directory structure for patch date. This was kind of pointless since we always want the latest patch set anyway
               1.5.0 * Convert stage 2: directory staging section to an array loop instead of static sequential commands
               1.4.0 - Remove Windows XP as an option due to Microsoft End-of-Life
               1.3.1 + Add line to echo what date we detected the last update occured on
               1.3.0 + Add functionality to update package deployment date in the PDQ job file
                     + Add section to check for existence of required files (PDQ xml job file, 7z.exe, 
                       and RunAll.cmd) before executing 
               1.2.0 / Change all instances of "-f" to "-f"
               1.1.0 + Add code to Step 2 to pre-clear the area on the server before uploading (remove old updates)
                     + Add Step 5: Re-calculate PDQ hashes
               1.0.0 + Initial write
 
 Usage:        Step 0: Run WSUS Offline at least once, choose your options, and generate the update script
               Step 1: Configure the variables below to reflect your set up (log location, repo location, etc)
               Step 2: Run this script
               Step 3: Re-import the XML job file in PDQ
#>


#############
# VARIABLES # -- Set these to your desired values or supply from the shell ---------------------- #
#############
# Rules for variables:
#  * Quotes are required              (e.g.:  "c:\directory\path"        )
#  * NO trailing slashes on paths!    (bad:   "c:\directory\"            )
#  * Spaces are okay                  (okay:  "c:\my folder\with spaces" )
#  * Network paths are okay           (okay:  "\\server\share name"      )
#                                     (       "\\172.16.1.5\share name"  )
param (
	# Logging information
	[string] $LOGPATH = $env:systemdrive + "\Logs",
	#[string] $LOGFILE = $env:computername + "_wsus_offline_update_deployer.log",
	[string] $LOGFILE = "deploy_wsus_offline_updates.log",
	
	# WSUS Offline root directory (where UpdateGenerator.exe is)
	[string] $WSUS_DIRECTORY = "p:\scripts\wsusoffline",                                                        # e.g. "c:\wsusoffline"
	# Path to the repo root on the server
	[string] $REPO_ROOT = "\\thebrain\Downloads\seeders\btsync\pdq_pack_microsoft_offline_updates\repository",  # e.g. "\\server\repo"
	
	# Path to the sub-directory containing updates
	[string[]]$PRODUCTS_NEW_NAMES = "office_2k7-2k16", "windows_7_and_server_2008-R2", "windows_8.1_and_server_2012-R2", "windows_10_and_server_2016",
	# Path to the sub-directory containing updates (old names)
	[string[]]$PRODUCTS_OLD_NAMES = "ofc", "w61-x64", "w63-x64", "w100-x64",
	# Path to the updates on the server
	[string] $REPO_UPDATES = "$REPO_ROOT\updates",
	# Path to the PDQ Deploy job file
	[string] $PDQ_JOB_FILE = "p:\scripts\pdq_deploy\Microsoft Offline Updates.xml",
	# Path to 7z.exe
	[string] $SEVENZIP = "c:\program files\7-zip\7z.exe",
	# Cleanup switch
	[string] $CLEANUP = "no"
)

# Set strict mode
Set-StrictMode -Version Latest




# ----------------------------- Don't edit anything below this line ----------------------------- #





########
# Prep #
########
$SCRIPT_VERSION = "1.5.4"
$CUR_DATE = Get-Date -Format "yyyy-MM-dd"

# Get the date of the last update so we find-replace the date in the PDQ job file later
Push-Location $REPO_UPDATES; Push-Location $PRODUCTS_NEW_NAMES[2]
#$PREVIOUS_UPDATE = ls -d | ForEach-Object{$_.Name} | sort -Descending | select -f 1         # This is the old method based on reading the directory name into a variable
$PREVIOUS_UPDATE = Get-Content ".\builddate.txt"
Pop-Location; Pop-Location


#################
# SANITY CHECKS #
#################
# Test for existence of 7-Zip
if (!(Test-Path $SEVENZIP)) {
	Write-Host ""
	Write-Host -NoNewline " ["; Write-Host -NoNewline "ERROR" -ForegroundColor red; Write-Host -NoNewline "]";
	Write-Host " Couldn't find 7z.exe at the location specified ( $SEVENZIP )"
	Write-Host "         Edit this script and change the `$SEVENZIP variable to point to 7z's location"
}

# Test for existence of RunAll.cmd, the WSUS update script
if (!(Test-Path "$WSUS_DIRECTORY\cmd\custom\RunAll.cmd")) {
	Write-Host ""
	Write-Host -NoNewline " ["; Write-Host -NoNewline "ERROR" -ForegroundColor red; Write-Host -NoNewline "]";
	Write-Host " Couldn't find RunAll.cmd, the WSUS Offline update script."
	Write-Host "         If you haven't already done so, you need to run WSUS Offline at least"
	Write-Host "         once and generate a RunAll.cmd based on the settings you choose."
}

# Test for existence of the PDQ Deploy job file
if (!(Test-Path $PDQ_JOB_FILE)) {
	Write-Host -NoNewline " ["; Write-Host -NoNewline "ERROR" -ForegroundColor red; Write-Host -NoNewline "]";
	Write-Host " Couldn't find the PDQ job file at the location specified:"
	Write-Host ""
	Write-Host "           $PDQ_JOB_FILE"
	Write-Host ""
	Write-Host "         If you haven't already done so, you need to launch PDQ Deploy and export"
	Write-Host "         this job file, then edit this script and change the `$PDQ_JOB_FILE variable"
	Write-Host "         to point to the location."
	Write-Host ""
}


#############
# EXECUTION #
#############
Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " WSUS Offline Package Deployer" -ForegroundColor green
Write-Host "                    Version: $SCRIPT_VERSION ($SCRIPT_UPDATED)" -ForegroundColor darkgray
Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Last pulldown detected on $PREVIOUS_UPDATE" -ForegroundColor green

"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " WSUS Offline Package Deployer" >> $LOGPATH\$LOGFILE
"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Version: $SCRIPT_VERSION ($SCRIPT_UPDATED)" >> $LOGPATH\$LOGFILE
"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Last pulldown detected on $PREVIOUS_UPDATE" >> $LOGPATH\$LOGFILE


##########
# Step 1 # -- Pull down the updates
##########
Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Pulling down updates..." -ForegroundColor green
"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Pulling down updates..." >> $LOGPATH\$LOGFILE

# Run the WSUS update script
Set-Location "$WSUS_DIRECTORY\cmd\custom"
& "RunAll.cmd"
Set-Location "$WSUS_DIRECTORY"

Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Done." -ForegroundColor darkgreen
"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Done." >> $LOGPATH\$LOGFILE


##########
# Step 2 # -- Unpack the ISOs and create the directory structure for upload
##########
Set-Location "$WSUS_DIRECTORY\iso"
Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Unpacking ISOs..." -ForegroundColor green
"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Unpacking ISOs..." >> $LOGPATH\$LOGFILE

# Unpack the ISOs
& $SEVENZIP x "$WSUS_DIRECTORY\iso\*.iso" -o* -y

Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Done." -ForegroundColor darkgreen
"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Done." >> $LOGPATH\$LOGFILE

# Create directory structure for upload
Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Staging directory structure for upload..." -ForegroundColor green
"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Staging directory structure for upload..." >> $LOGPATH\$LOGFILE

# Pre-stage the directories since "move-item" is stupid and has no option to create them on the fly
foreach ($i in $PRODUCTS_NEW_NAMES) {
	New-Item -Path ".\$i\" -ItemType Directory -Force | Out-Null
	Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Staged $i." -ForegroundColor darkgray
	"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Staged $i." >> $LOGPATH\$LOGFILE
}

# Move everything into the new directories
for ($i = 0; $i -lt $PRODUCTS_OLD_NAMES.Count; $i++) {
	Move-Item ".\$($PRODUCTS_OLD_NAMES[$i])\*" ".\$($PRODUCTS_NEW_NAMES[$i])"
}

# Delete the old directories (local)
foreach ($i in $PRODUCTS_OLD_NAMES) {
	Remove-Item $i -Force -Recurse
}

# Done
Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Done." -ForegroundColor darkgreen
"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Done." >> $LOGPATH\$LOGFILE

# Delete the old directories (server-side)
Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Clearing upload target area..." -ForegroundColor green
"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Clearing upload target area..." >> $LOGPATH\$LOGFILE
foreach ($i in $PRODUCTS_NEW_NAMES) {
	Remove-Item "$REPO_UPDATES\$i" -Force -Recurse | Out-Null
}
	
# Done
Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Done." -ForegroundColor darkgreen
"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Done." >> $LOGPATH\$LOGFILE


##########
# Step 3 # -- Upload the updates to their respective directories on the server
##########
Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Uploading files to repository at $REPO_ROOT..." -ForegroundColor green
"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Uploading files to repository at $REPO_ROOT..." >> $LOGPATH\$LOGFILE

# This loop iterates through the list of directory names and uploads them using Robocopy
foreach ($i in $PRODUCTS_NEW_NAMES) {
	Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Uploading $i..." -ForegroundColor green
	"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Uploading $i..." >> $LOGPATH\$LOGFILE
	robocopy ".\$i" "$REPO_UPDATES\$i" /R:3 /W:5 /mir /NP /NJH /NJS >> $LOGPATH\$LOGFILE
	Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Done." -ForegroundColor darkgreen
}

# Done with all uploads
Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " All uploads done." -ForegroundColor darkgreen
"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " All uploads done." >> $LOGPATH\$LOGFILE


###########
# Step 3a # -- cleanup
###########
IF ($CLEANUP -eq "yes") { 
	Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " `$CLEANUP variable set to yes. Performing cleanup." -ForegroundColor green
	"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " `$CLEANUP variable set to yes. Performing cleanup." >> $LOGPATH\$LOGFILE
	Remove-Item * -Force -Recurse
	Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Done. Deleted everything in $WSUS_DIRECTORY\iso" -ForegroundColor darkgreen
	"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Done. Deleted everything in $WSUS_DIRECTORY\iso" >> $LOGPATH\$LOGFILE
}
ELSE {
	Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " `$CLEANUP variable not set to yes. Skipping cleanup." -ForegroundColor darkgreen
	"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " `$CLEANUP variable not set to yes. Skipping cleanup." >> $LOGPATH\$LOGFILE
}


##########
# Step 4 # -- Update PDQ xml job file
##########
Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Updating PDQ job file to current date..." -ForegroundColor green
"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Updating PDQ job file to current date..." >> $LOGPATH\$LOGFILE

# Do a find-replace on the date string in the PDQ job file
(Get-Content "$PDQ_JOB_FILE") | ForEach-Object { $_ -replace ($PREVIOUS_UPDATE), "$CUR_DATE" } | Set-Content $PDQ_JOB_FILE -Force

Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Done." -ForegroundColor darkgreen
"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Done." >> $LOGPATH\$LOGFILE


##########
# Step 5 # -- Recalculate hashes
##########
Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Recalculating hashes, please wait..." -ForegroundColor green
"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Recalculating hashes, please wait..." >> $LOGPATH\$LOGFILE
Set-Location $REPO_ROOT
Set-Location ..
Set-Location "integrity verification"
Remove-Item checksum* -Force -Recurse | Out-Null
Remove-Item "$env:temp\checksum*" -Force -Recurse | Out-Null
Set-Location ..
hashdeep -c md5 -r -l * > "$env:temp\checksums.txt"
Move-Item "$env:temp\checksums.txt" "integrity verification\checksums.txt"
# Done
Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " Done." -ForegroundColor darkgreen
"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " Done." >> $LOGPATH\$LOGFILE



############
# Finished #
############
Write-Host $CUR_DATE (Get-Date -Format hh:mm:ss) -NoNewline -ForegroundColor darkgray; Write-Host " DONE. Make sure to re-import the updated PDQ job file." -ForegroundColor green
Write-Host "                    Working directory:  $WSUS_DIRECTORY" -ForegroundColor darkgray
Write-Host "                    Target repo:        $REPO_ROOT" -ForegroundColor darkgray
Write-Host "                    PDQ job file:       $PDQ_JOB_FILE" -ForegroundColor darkgray
Write-Host "                    Log file:           $LOGPATH\$LOGFILE" -ForegroundColor darkgray
Write-Host "                    Cleanup performed?: $CLEANUP" -ForegroundColor darkgray

"$CUR_DATE " + $(Get-Date -Format hh:mm:ss) + " DONE. Make sure to re-import the updated PDQ job file." >> $LOGPATH\$LOGFILE
Write-Output "                    Working directory:   $WSUS_DIRECTORY" >> $LOGPATH\$LOGFILE
Write-Output "                    Target repo:         $REPO_ROOT" >> $LOGPATH\$LOGFILE
Write-Output "                    PDQ job file:        $PDQ_JOB_FILE" >> $LOGPATH\$LOGFILE
Write-Output "                    Log file:            $LOGPATH\$LOGFILE" >> $LOGPATH\$LOGFILE
Write-Output "                    Cleanup performed?:  $CLEANUP" >> $LOGPATH\$LOGFILE
